import {useEffect,useRef,useState} from 'react'
import {BookOpen,ChevronDown,ChevronLeft,ChevronRight,Search,X} from 'lucide-react'
import {CATEGORIES,PAPERS,paperById,type PaperId,type PaperCategory} from '../papers'
import './paperLibrary.css'
export function PaperLibrary({active,onSelect}:{active:PaperId;onSelect:(id:PaperId)=>void}){
 const [open,setOpen]=useState(true),[category,setCategory]=useState<PaperCategory|'all'>(()=>paperById(active)!.category),[query,setQuery]=useState(''),input=useRef<HTMLInputElement>(null)
 const current=paperById(active)!,index=PAPERS.findIndex(p=>p.id===active)
 const results=PAPERS.filter(p=>(category==='all'||p.category===category)&&`${p.short} ${p.title} ${p.topic} ${p.authors}`.toLowerCase().includes(query.trim().toLowerCase()))
 const select=(id:PaperId)=>{onSelect(id);setOpen(false)}
 useEffect(()=>{setCategory(paperById(active)!.category)},[active])
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true);setCategory('all');requestAnimationFrame(()=>input.current?.focus())}if(e.key==='Escape'&&open){setOpen(false)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open])
 return <nav className="paper-library section-shell" aria-label="文献档案导航">
  <div className="paper-library-bar"><button className="paper-library-toggle" aria-expanded={open} aria-controls="paper-library-catalog" onClick={()=>setOpen(v=>!v)}><BookOpen size={19}/><span>文献档案<small>{PAPERS.length} 篇 / {CATEGORIES.length} 个栏目</small></span><ChevronDown size={16}/></button><div className="paper-current"><span>{CATEGORIES.find(c=>c.id===current.category)!.title}</span><strong>{current.short}</strong></div><div className="paper-quick-nav"><button disabled={index===0} aria-label="上一篇文献" title="上一篇" onClick={()=>select(PAPERS[index-1].id)}><ChevronLeft size={17}/></button><button disabled={index===PAPERS.length-1} aria-label="下一篇文献" title="下一篇" onClick={()=>select(PAPERS[index+1].id)}><ChevronRight size={17}/></button></div></div>
  {open&&<div id="paper-library-catalog" className="paper-library-catalog"><div className="paper-library-tools"><label><Search size={17}/><input ref={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索论文、作者或研究关键词" aria-label="搜索文献"/><kbd>Ctrl K</kbd></label>{query&&<button aria-label="清空文献搜索" onClick={()=>setQuery('')}><X size={16}/></button>}<span role="status">{results.length} 篇匹配</span></div><div className="paper-library-body"><div className="paper-categories" aria-label="文献栏目"><button aria-pressed={category==='all'} onClick={()=>setCategory('all')}>全部文献<span>{PAPERS.length}</span></button>{CATEGORIES.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}><strong>{c.title}</strong><small>{c.description}</small><span>{PAPERS.filter(p=>p.category===c.id).length}</span></button>)}</div><div className="paper-library-results" role="tablist" aria-label="选择文献笔记" aria-orientation="vertical">{results.map((p,i)=><button key={p.id} role="tab" id={`tab-${p.id}`} aria-selected={active===p.id} aria-controls={`panel-${p.id}`} tabIndex={p.id===(results.some(r=>r.id===active)?active:results[0]?.id)?0:-1} onClick={()=>select(p.id)} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?results.length-1:(i+(e.key==='ArrowDown'?1:-1)+results.length)%results.length;document.getElementById(`tab-${results[next].id}`)?.focus()}}}><div><strong>{p.short}</strong><span>{p.venue}</span></div><p>{p.title}</p><small>{p.topic}</small><em>{p.repo?'作者源码':'论文架构 · 待公开源码'}</em><ChevronRight size={18}/></button>)}{results.length===0&&<div className="paper-search-empty"><p>没有找到匹配文献。</p><button onClick={()=>{setCategory('all');setQuery('')}}>查看全部文献</button></div>}</div></div></div>}
 </nav>
}
